name: tracker_flutter_annotations
description: >
  Annotations for the trackable code-generator.
  This package does nothing without trackable too.
version: 0.0.1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9

