targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":tracker_generators"
    import: "package:tracker_generators/tracker_generators.dart"
    builder_factories: ["trackable"] #Builder name(BuilderOptions)
    build_extensions: { ".dart": [".trackable.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
