name: tracker_generators
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.0.1
repository: https://github.com/phonghoang2k/tracker_generator

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  tracker_annotations: ^0.0.1
  analyzer: ^6.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner:



