name: tracker_generators
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.0.1
repository: https://github.com/phonghoang2k/tracker_generator
publish_to: none

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  build:
  source_gen: ^1.5.0
  tracker_annotations:
    path: ../annotations

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner:



